### ISSUE TITLE
Arithmetic Overflow issue

### ISSUE THREAD

**Issue by SteAmeR** [EricZimmerman/ExtensionBlocks#4]
Hi Eric,

> Note: This issue is related to [LNK Repository Issue 8](https://github.com/EricZimmerman/Lnk/issues/8 ) which opened where in the "LNK" repository yesterday.

An unexceptional throw occurs while processing a value of integer that includes buffer size. The exception occurs when this value of buffer.length is used with the 'Array.Copy' argument code on line 30 in  PropertyStore.cs  and line 305 in PropertySheet.cs.

I want to send a "Pull Request" to based on your consent.

**Comment by EricZimmerman** [comment]
Nice. I'll take a look and accept these here today

**Comment by SteAmeR** [comment]
> Nice. I'll take a look and accept these here today

Any progress :)

**Comment by EricZimmerman** [comment]
I've been teaching the past week, even the weekend here, so I hope I can do this for you today around 11 or so.

**Comment by EricZimmerman** [comment]
done

**Comment by SteAmeR** [comment]
> done

I appreciate your help. Thank you.
