### ISSUE TITLE
Exception throw while parsing null byte array on GetStringsFromMultistring

### ISSUE THREAD

**Issue by SteAmeR** [EricZimmerman/ExtensionBlocks#7]
Hi Eric,

I came across a new malicious lnk sample on wild but it throw an exception when I tried parsing by LNK project because GetStringsFromMultistring function on Utility.cs doesn't check properly to the byte array that is given to it as an argument. If the byte array filled with 0x00 (zero) then calculation (instancePosition - index) is wrong! Because the index can be a negative number! 

I fixed the problem by adding an "if condition" at the beginning of the function that checks for zero bytes.

**Comment by AndrewRathbun** [comment]
@SteAmeR any chance you're going to do a PR for this?

**Comment by SteAmeR** [comment]
> @SteAmeR any chance you're going to do a PR for this?

sure https://github.com/EricZimmerman/ExtensionBlocks/pull/8

**Comment by EricZimmerman** [comment]
ill push a new package asap.

**Comment by EricZimmerman** [comment]
1.3.2 pushed.
